version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    volumes:
      - kafka_vol:/kafka/data
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_MINUTES: 15
      KAFKA_CREATE_TOPICS: "tweets:1:1"
  twitter_connect:
    build: twitter-connect
    depends_on:
      - kafka
    container_name: twitter-connect
    hostname: twitter-connect
  sope-spark-streaming:
    build: .
    container_name: sse
    depends_on:
      - kafka
volumes:
     kafka_vol: